version: '{build}'
image: Visual Studio 2019
configuration:
- Release
platform: x64
build:
  project: source-code/PD-Loader.sln
  verbosity: minimal
after_build:
- ps: .\package.ps1 -Clean:$false
artifacts:
- path: PD-Loader-*.zip
